In [1]:
import codecs
import csv
import time
import os
import re
import gzip
import pandas as pd
import numpy as np

In [2]:
PATH_TO_DATA = 'Data/'
PATH_TO_DATA_EN = PATH_TO_DATA+"enwiki/"
PATH_TO_DATA_UK = PATH_TO_DATA+"ukwiki/"

In [3]:
ENWIKI_ART_FNMS = []
for file in os.listdir(PATH_TO_DATA_EN):
    if re.match(r"enwiki-20180620-pages-meta-current\d{2}-p\d+p\d+.xml_art.csv.gz", file):
        ENWIKI_ART_FNMS.append(file)
ENWIKI_RED_FNMS = []
for file in os.listdir(PATH_TO_DATA_EN):
    if re.match(r"enwiki-20180620-pages-meta-current\d{2}-p\d+p\d+.xml_red.csv.gz", file):
        ENWIKI_RED_FNMS.append(file)

In [4]:
def unpack(file_name):
    file_name_new = file_name.replace(".gz","")
    with gzip.open(file_name, 'rb') as f_in, open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    return file_name_new

In [5]:
def pack_and_remove(file_name):
    file_name_new = file_name+'.gz'
    with open(file_name, 'rb') as f_in, gzip.open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    os.remove(file_name)
    return file_name_new

In [6]:
df_title_count = None
for fn in ENWIKI_ART_FNMS:
    fn = PATH_TO_DATA_EN+fn
    print(fn)
    fn_new = unpack(fn)
    df_articles = pd.read_csv(fn_new, encoding='ISO-8859-1',quotechar="'")

    df_red_links = df_articles[df_articles['is_red_link'] == True]
    df_title_count_tmp = pd.DataFrame(df_red_links.groupby('link_val').link_val.count())
    df_title_count_tmp.columns = ['link']
    df_title_count_tmp = df_title_count_tmp.reset_index(col_level=1)
    df_title_count_tmp.columns = ['link_title', 'in_count']
    
    if df_title_count is not None:
        df_title_count = df_title_count.append(df_title_count_tmp)        
        #print("append")
    else:
        df_title_count = df_title_count_tmp
        #print("assign")    
    df_title_count = df_title_count.groupby('link_title').in_count.sum().copy()
    df_title_count.columns = ['link']
    df_title_count = df_title_count.reset_index()
    df_title_count.columns = ['link_title', 'in_count']        
    print("df_title_count size: {}".format(df_title_count.shape))
    os.remove(fn_new)

Data/enwiki/enwiki-20180620-pages-meta-current01-p10p30303.xml_art.csv.gz
df_title_count size: (26887, 2)
Data/enwiki/enwiki-20180620-pages-meta-current02-p30304p88444.xml_art.csv.gz
df_title_count size: (73462, 2)
Data/enwiki/enwiki-20180620-pages-meta-current03-p88445p200507.xml_art.csv.gz
df_title_count size: (146899, 2)
Data/enwiki/enwiki-20180620-pages-meta-current04-p200511p352689.xml_art.csv.gz
df_title_count size: (246012, 2)
Data/enwiki/enwiki-20180620-pages-meta-current05-p352690p565313.xml_art.csv.gz
df_title_count size: (368615, 2)
Data/enwiki/enwiki-20180620-pages-meta-current06-p565314p892912.xml_art.csv.gz
df_title_count size: (492089, 2)
Data/enwiki/enwiki-20180620-pages-meta-current07-p892914p1268691.xml_art.csv.gz
df_title_count size: (631762, 2)
Data/enwiki/enwiki-20180620-pages-meta-current08-p1268692p1791079.xml_art.csv.gz
df_title_count size: (786642, 2)
Data/enwiki/enwiki-20180620-pages-meta-current09-p1791080p2336422.xml_art.csv.gz
df_title_count size: (944630, 2)
Data/enwiki/enwiki-20180620-pages-meta-current10-p2336425p3046511.xml_art.csv.gz
df_title_count size: (1112121, 2)
Data/enwiki/enwiki-20180620-pages-meta-current11-p3046514p3926861.xml_art.csv.gz
df_title_count size: (1302407, 2)
Data/enwiki/enwiki-20180620-pages-meta-current12-p3926863p5040436.xml_art.csv.gz
df_title_count size: (1483401, 2)
Data/enwiki/enwiki-20180620-pages-meta-current13-p5040438p6197594.xml_art.csv.gz
df_title_count size: (1690792, 2)
Data/enwiki/enwiki-20180620-pages-meta-current14-p6197598p7697598.xml_art.csv.gz
df_title_count size: (1861124, 2)
Data/enwiki/enwiki-20180620-pages-meta-current14-p7697598p7744799.xml_art.csv.gz
df_title_count size: (1866941, 2)
Data/enwiki/enwiki-20180620-pages-meta-current15-p7744803p9244803.xml_art.csv.gz
df_title_count size: (2036852, 2)
Data/enwiki/enwiki-20180620-pages-meta-current15-p9244803p9518048.xml_art.csv.gz
df_title_count size: (2062308, 2)
Data/enwiki/enwiki-20180620-pages-meta-current16-p11018050p11539266.xml_art.csv.gz
df_title_count size: (2112392, 2)
Data/enwiki/enwiki-20180620-pages-meta-current16-p9518050p11018050.xml_art.csv.gz
df_title_count size: (2263800, 2)
Data/enwiki/enwiki-20180620-pages-meta-current17-p11539268p13039268.xml_art.csv.gz
df_title_count size: (2449781, 2)
Data/enwiki/enwiki-20180620-pages-meta-current17-p13039268p13693071.xml_art.csv.gz
df_title_count size: (2506740, 2)
Data/enwiki/enwiki-20180620-pages-meta-current18-p13693074p15193074.xml_art.csv.gz
df_title_count size: (2656135, 2)
Data/enwiki/enwiki-20180620-pages-meta-current18-p15193074p16120542.xml_art.csv.gz
df_title_count size: (2727973, 2)
Data/enwiki/enwiki-20180620-pages-meta-current19-p16120543p17620543.xml_art.csv.gz
df_title_count size: (2828126, 2)
Data/enwiki/enwiki-20180620-pages-meta-current19-p17620543p18754735.xml_art.csv.gz
df_title_count size: (2913960, 2)
Data/enwiki/enwiki-20180620-pages-meta-current20-p18754736p20254736.xml_art.csv.gz
df_title_count size: (3029918, 2)
Data/enwiki/enwiki-20180620-pages-meta-current20-p20254736p21222156.xml_art.csv.gz
df_title_count size: (3102057, 2)
Data/enwiki/enwiki-20180620-pages-meta-current21-p21222158p22722158.xml_art.csv.gz
df_title_count size: (3250997, 2)
Data/enwiki/enwiki-20180620-pages-meta-current21-p22722158p23927983.xml_art.csv.gz
df_title_count size: (3364053, 2)
Data/enwiki/enwiki-20180620-pages-meta-current22-p23927984p25427984.xml_art.csv.gz
df_title_count size: (3521905, 2)
Data/enwiki/enwiki-20180620-pages-meta-current22-p25427984p26823660.xml_art.csv.gz
df_title_count size: (3639138, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p26823661p28323661.xml_art.csv.gz
df_title_count size: (3769859, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p28323661p29823661.xml_art.csv.gz
df_title_count size: (3881855, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p29823661p30503449.xml_art.csv.gz
df_title_count size: (3924815, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p30503451p32003451.xml_art.csv.gz
df_title_count size: (4067065, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p32003451p33503451.xml_art.csv.gz
df_title_count size: (4219423, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p33503451p33952815.xml_art.csv.gz
df_title_count size: (4261762, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p33952816p35452816.xml_art.csv.gz
df_title_count size: (4361697, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p35452816p36952816.xml_art.csv.gz
df_title_count size: (4482402, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p36952816p38067202.xml_art.csv.gz
df_title_count size: (4561163, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p38067203p39567203.xml_art.csv.gz
df_title_count size: (4670439, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p39567203p41067203.xml_art.csv.gz
df_title_count size: (4781810, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p41067203p42567203.xml_art.csv.gz
df_title_count size: (4888658, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p42567203p42663461.xml_art.csv.gz
df_title_count size: (4895197, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p42663462p44163462.xml_art.csv.gz
df_title_count size: (5011588, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p44163462p45663462.xml_art.csv.gz
df_title_count size: (5113310, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p45663462p47163462.xml_art.csv.gz
df_title_count size: (5181343, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p47163462p48663462.xml_art.csv.gz
df_title_count size: (5270831, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p48663462p50163462.xml_art.csv.gz
df_title_count size: (5357973, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p50163462p51663462.xml_art.csv.gz
df_title_count size: (5452684, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p51663462p53163462.xml_art.csv.gz
df_title_count size: (5526583, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p53163462p54663462.xml_art.csv.gz
df_title_count size: (5609987, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p54663462p56163462.xml_art.csv.gz
df_title_count size: (5711934, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p56163462p57663462.xml_art.csv.gz
df_title_count size: (5823405, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p57663462p57726175.xml_art.csv.gz
df_title_count size: (5826322, 2)

In [7]:
df_title_count = df_title_count.sort_values(['in_count'], ascending=[0])

In [8]:
df_title_count.to_csv(PATH_TO_DATA_EN+'enwiki-20180620-red_name_count.csv', index = False, encoding='ISO-8859-1', quotechar="'", escapechar ="\\")

In [9]:
df_title_count

                                         link_title  in_count
36                                                       6572
5684449                                          ]]      6023
3096939          List of South Korean films of 19xx      4451
5789221                               {{Fb position      2530
5107262                                    The Poll      1547
4086564  Philippine general election, {{PH wikidata      1463
5789234                               {{PH wikidata      1420
4528516                             Saaremaa Parish       841
5789251                               {{fb position       633
5789263                                           |       620
2367262                                  INGEOMINAS       569
296769                                Airport Name1       444
5805137                                      Ã©pÃ©e       430
5028809                     Technical Sports Racing       385
3915474                        OurSportsCentral.com       377
2437442                         Iran Daylight Time        371
9825                                       District       367
5684534                                   ]]'''''         355
4867048                              State/Province       340
577878               Association_football_positions       316
5789559                                         Âµm       302
1214581                              Conny Kissling       300
5331966       University of Wisconsin&ndash;Madison       300
1939661                                    GameZone       298
4151314                             Pocono ARCA 200       294
5805111                                    Ã©migrÃ©       287
3730621                                 Ng Chiu Kok       287
5545204       Wilson JosÃ© Eduardo Moreira da Costa       279
4209523                               Producer name       277
5546659                         Winchester ARCA 200       273
...                                             ...       ...
2204386                           Havana is Waiting         1
2204385                     Havana giant blindsnake         1
2204383           Havana bids for the Olympic Games         1
2204379              Havana Yellow Fever Commission         1
2204378        Havana Water and Sanitation District         1
2204377             Havana TulipÃ¡n railway station         1
2204375                                Havana Stars         1
2204373                                Havana Rocks         1
2204372                     Havana Regional Airport         1
2204371                                 Havana Reds         1
2204370                              Havana Red Sox         1
2204393                            Havana, Windhoek         1
2204394                                 Havana,Cuba         1
2204396                                  Havanawela         1
2204407                   Havanna (Windhoek suburb)         1
2204415                  Havant & Waterlooville LFC         1
2204414                                      Havans         1
2204413                    Havannah Weetslade Fault         1
2204411                      Havanna Street, Odessa         1
2204410                             Havanna Harbour         1
2204409                            Havanna Biennial         1
2204406                     Havanitos (cigar brand)         1
2204398                                    Havanera         1
2204405                      Havanirooz Tabriz Base         1
2204404                     Havanirooz Mashhad Base         1
2204403                  Havanirooz 4th Combat Base         1
2204402                  Havanirooz 2nd Combat Base         1
2204401                               Havanir Nimtz         1
2204400                    Havanese Club of America         1
5826321                                        ð«         1

[5826322 rows x 2 columns]

In [10]:
df_title_count.describe()

           in_count
count  5.826322e+06
mean   1.671689e+00
std    5.195138e+00
min    1.000000e+00
25%    1.000000e+00
50%    1.000000e+00
75%    2.000000e+00
max    6.572000e+03

In [11]:
df_count_by_count = pd.DataFrame(df_title_count.groupby('in_count').in_count.count())

In [12]:
df_count_by_count.columns = ['link']
df_count_by_count = df_count_by_count.reset_index()
df_count_by_count.columns = ['count', 'in_count']

In [13]:
df_count_by_count = df_count_by_count.sort_values(['count'], ascending=[1])

In [14]:
df_count_by_count

     count  in_count
0        1   4365576
1        2    813513
2        3    268516
3        4    130033
4        5     69864
5        6     44644
6        7     29389
7        8     20781
8        9     15277
9       10     11658
10      11      8985
11      12      7094
12      13      5466
13      14      4698
14      15      3722
15      16      3109
16      17      2621
17      18      2170
18      19      1917
19      20      1707
20      21      1387
21      22      1253
22      23      1099
23      24       972
24      25       867
25      26       756
26      27       666
27      28       621
28      29       541
29      30       532
..     ...       ...
206    263         1
207    266         1
208    273         1
209    277         1
210    279         1
211    287         2
212    294         1
213    298         1
214    300         2
215    302         1
216    316         1
217    340         1
218    355         1
219    367         1
220    371         1
221    377         1
222    385         1
223    430         1
224    444         1
225    569         1
226    620         1
227    633         1
228    841         1
229   1420         1
230   1463         1
231   1547         1
232   2530         1
233   4451         1
234   6023         1
235   6572         1

[236 rows x 2 columns]

In [15]:
df_count_by_count.describe()

             count      in_count
count   236.000000  2.360000e+02
mean    234.245763  2.468781e+04
std     673.407106  2.893426e+05
min       1.000000  1.000000e+00
25%      59.750000  1.000000e+00
50%     118.500000  6.000000e+00
75%     189.250000  6.275000e+01
max    6572.000000  4.365576e+06

In [16]:
df_count_by_count.to_csv(PATH_TO_DATA_EN+'enwiki-20180620-red_count_by_count.csv', index = False, encoding='ISO-8859-1', quotechar="'", escapechar ="\\")