In [1]:
import codecs
import csv
import time
import os
import re
import gzip
import pandas as pd
import numpy as np

In [2]:
PATH_TO_DATA = 'Data/'
PATH_TO_DATA_EN = PATH_TO_DATA+"enwiki/"
PATH_TO_DATA_UK = PATH_TO_DATA+"ukwiki/"

In [3]:
ENWIKI_ART_FNMS = []
for file in os.listdir(PATH_TO_DATA_EN):
    if re.match(r"enwiki-20180620-pages-meta-current\d{2}-p\d+p\d+.xml_art.csv.gz", file):
        ENWIKI_ART_FNMS.append(file)
ENWIKI_RED_FNMS = []
for file in os.listdir(PATH_TO_DATA_EN):
    if re.match(r"enwiki-20180620-pages-meta-current\d{2}-p\d+p\d+.xml_red.csv.gz", file):
        ENWIKI_RED_FNMS.append(file)

In [4]:
def unpack(file_name):
    file_name_new = file_name.replace(".gz","")
    with gzip.open(file_name, 'rb') as f_in, open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    return file_name_new

In [5]:
def pack_and_remove(file_name):
    file_name_new = file_name+'.gz'
    with open(file_name, 'rb') as f_in, gzip.open(file_name_new, 'wb') as f_out:
        f_out.writelines(f_in)
    os.remove(file_name)
    return file_name_new

In [50]:
df_title_count = None
for fn in ENWIKI_ART_FNMS:
    fn = PATH_TO_DATA_EN+fn
    print(fn)
    fn_new = unpack(fn)
    df_articles = pd.read_csv(fn_new, encoding='ISO-8859-1',quotechar="'")

    df_red_links = df_articles[df_articles['is_red_link'] == True]
    df_title_count_tmp = pd.DataFrame(df_red_links.groupby('link_val').link_val.count())
    df_title_count_tmp.columns = ['link']
    df_title_count_tmp = df_title_count_tmp.reset_index(col_level=1)
    df_title_count_tmp.columns = ['link_title', 'in_count']
    
    if df_title_count is not None:
        df_title_count = df_title_count.append(df_title_count_tmp)        
        #print("append")
    else:
        df_title_count = df_title_count_tmp
        #print("assign")    
    df_title_count = df_title_count.groupby('link_title').in_count.sum().copy()
    df_title_count.columns = ['link']
    df_title_count = df_title_count.reset_index()
    df_title_count.columns = ['link_title', 'in_count']        
    print("df_title_count size: {}".format(df_title_count.shape))
    os.remove(fn_new)

Data/enwiki/enwiki-20180620-pages-meta-current01-p10p30303.xml_art.csv.gz
df_title_count size: (282312, 2)
Data/enwiki/enwiki-20180620-pages-meta-current02-p30304p88444.xml_art.csv.gz
df_title_count size: (534722, 2)
Data/enwiki/enwiki-20180620-pages-meta-current03-p88445p200507.xml_art.csv.gz
df_title_count size: (804663, 2)
Data/enwiki/enwiki-20180620-pages-meta-current04-p200511p352689.xml_art.csv.gz
df_title_count size: (1124147, 2)
Data/enwiki/enwiki-20180620-pages-meta-current05-p352690p565313.xml_art.csv.gz
df_title_count size: (1448244, 2)
Data/enwiki/enwiki-20180620-pages-meta-current06-p565314p892912.xml_art.csv.gz
df_title_count size: (1757356, 2)
Data/enwiki/enwiki-20180620-pages-meta-current07-p892914p1268691.xml_art.csv.gz
df_title_count size: (2063623, 2)
Data/enwiki/enwiki-20180620-pages-meta-current08-p1268692p1791079.xml_art.csv.gz
df_title_count size: (2386929, 2)
Data/enwiki/enwiki-20180620-pages-meta-current09-p1791080p2336422.xml_art.csv.gz
df_title_count size: (2688086, 2)
Data/enwiki/enwiki-20180620-pages-meta-current10-p2336425p3046511.xml_art.csv.gz
df_title_count size: (2985740, 2)
Data/enwiki/enwiki-20180620-pages-meta-current11-p3046514p3926861.xml_art.csv.gz
df_title_count size: (3307354, 2)
Data/enwiki/enwiki-20180620-pages-meta-current12-p3926863p5040436.xml_art.csv.gz
df_title_count size: (3613793, 2)
Data/enwiki/enwiki-20180620-pages-meta-current13-p5040438p6197594.xml_art.csv.gz
df_title_count size: (3938346, 2)
Data/enwiki/enwiki-20180620-pages-meta-current14-p6197598p7697598.xml_art.csv.gz
df_title_count size: (4210554, 2)
Data/enwiki/enwiki-20180620-pages-meta-current14-p7697598p7744799.xml_art.csv.gz
df_title_count size: (4219635, 2)
Data/enwiki/enwiki-20180620-pages-meta-current15-p7744803p9244803.xml_art.csv.gz
df_title_count size: (4479066, 2)
Data/enwiki/enwiki-20180620-pages-meta-current15-p9244803p9518048.xml_art.csv.gz
df_title_count size: (4517332, 2)
Data/enwiki/enwiki-20180620-pages-meta-current16-p11018050p11539266.xml_art.csv.gz
df_title_count size: (4596023, 2)
Data/enwiki/enwiki-20180620-pages-meta-current16-p9518050p11018050.xml_art.csv.gz
df_title_count size: (4816911, 2)
Data/enwiki/enwiki-20180620-pages-meta-current17-p11539268p13039268.xml_art.csv.gz
df_title_count size: (5081684, 2)
Data/enwiki/enwiki-20180620-pages-meta-current17-p13039268p13693071.xml_art.csv.gz
df_title_count size: (5164859, 2)
Data/enwiki/enwiki-20180620-pages-meta-current18-p13693074p15193074.xml_art.csv.gz
df_title_count size: (5378842, 2)
Data/enwiki/enwiki-20180620-pages-meta-current18-p15193074p16120542.xml_art.csv.gz
df_title_count size: (5483113, 2)
Data/enwiki/enwiki-20180620-pages-meta-current19-p16120543p17620543.xml_art.csv.gz
df_title_count size: (5639832, 2)
Data/enwiki/enwiki-20180620-pages-meta-current19-p17620543p18754735.xml_art.csv.gz
df_title_count size: (5768832, 2)
Data/enwiki/enwiki-20180620-pages-meta-current20-p18754736p20254736.xml_art.csv.gz
df_title_count size: (5940314, 2)
Data/enwiki/enwiki-20180620-pages-meta-current20-p20254736p21222156.xml_art.csv.gz
df_title_count size: (6044157, 2)
Data/enwiki/enwiki-20180620-pages-meta-current21-p21222158p22722158.xml_art.csv.gz
df_title_count size: (6247368, 2)
Data/enwiki/enwiki-20180620-pages-meta-current21-p22722158p23927983.xml_art.csv.gz
df_title_count size: (6403401, 2)
Data/enwiki/enwiki-20180620-pages-meta-current22-p23927984p25427984.xml_art.csv.gz
df_title_count size: (6612984, 2)
Data/enwiki/enwiki-20180620-pages-meta-current22-p25427984p26823660.xml_art.csv.gz
df_title_count size: (6775029, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p26823661p28323661.xml_art.csv.gz
df_title_count size: (6952620, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p28323661p29823661.xml_art.csv.gz
df_title_count size: (7102151, 2)
Data/enwiki/enwiki-20180620-pages-meta-current23-p29823661p30503449.xml_art.csv.gz
df_title_count size: (7161880, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p30503451p32003451.xml_art.csv.gz
df_title_count size: (7353227, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p32003451p33503451.xml_art.csv.gz
df_title_count size: (7548323, 2)
Data/enwiki/enwiki-20180620-pages-meta-current24-p33503451p33952815.xml_art.csv.gz
df_title_count size: (7603399, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p33952816p35452816.xml_art.csv.gz
df_title_count size: (7741530, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p35452816p36952816.xml_art.csv.gz
df_title_count size: (7903245, 2)
Data/enwiki/enwiki-20180620-pages-meta-current25-p36952816p38067202.xml_art.csv.gz
df_title_count size: (8010001, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p38067203p39567203.xml_art.csv.gz
df_title_count size: (8159479, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p39567203p41067203.xml_art.csv.gz
df_title_count size: (8309139, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p41067203p42567203.xml_art.csv.gz
df_title_count size: (8451336, 2)
Data/enwiki/enwiki-20180620-pages-meta-current26-p42567203p42663461.xml_art.csv.gz
df_title_count size: (8459759, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p42663462p44163462.xml_art.csv.gz
df_title_count size: (8610326, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p44163462p45663462.xml_art.csv.gz
df_title_count size: (8743921, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p45663462p47163462.xml_art.csv.gz
df_title_count size: (8833856, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p47163462p48663462.xml_art.csv.gz
df_title_count size: (8948199, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p48663462p50163462.xml_art.csv.gz
df_title_count size: (9062833, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p50163462p51663462.xml_art.csv.gz
df_title_count size: (9184812, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p51663462p53163462.xml_art.csv.gz
df_title_count size: (9281703, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p53163462p54663462.xml_art.csv.gz
df_title_count size: (9388839, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p54663462p56163462.xml_art.csv.gz
df_title_count size: (9511291, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p56163462p57663462.xml_art.csv.gz
df_title_count size: (9651304, 2)
Data/enwiki/enwiki-20180620-pages-meta-current27-p57663462p57726175.xml_art.csv.gz
df_title_count size: (9655165, 2)

In [66]:
df_title_count.to_csv(PATH_TO_DATA_EN+'enwiki-20180620-red_name_count.csv', index = False, encoding='ISO-8859-1', quotechar="'", escapechar ="\\")

In [59]:
df_title_count = df_title_count.sort_values(['in_count'], ascending=[0])

In [60]:
df_title_count

                                                link_title  in_count
756375                                            Allmusic     79292
2101603                             Countries of the world     68096
4932857                                  List of countries     63259
7047750                            Rural Districts of Iran     63203
3928707                                 Iran Daylight Time     59854
6734046                        Race (United States Census)     58224
8964302                               association football     54693
6990032                                           Romanize     54656
9391627                                 population density     46853
5424485                               Member of Parliament     42947
8874657                                           ZIP code     41628
8670935                                White (U.S. Census)     39553
2920293            Federal Information Processing Standard     39231
9395567                                       poverty line     35283
9370961                                  per capita income     34880
3670734                             Hispanic (U.S. Census)     34668
4709577                               Latino (U.S. Census)     34521
7640590                    States and territories of India     34160
872828                                         Angiosperms     31867
9315574                                               moth     31774
5827413                      Native American (U.S. Census)     30296
9491058                                            species     29421
9187662                                             guitar     29221
605638                      African American (U.S. Census)     28296
1032387                                Asian (U.S. Census)     27558
5895361                                     New York Times     27188
878607                                            Animalia     27134
6983714                                     Roman Catholic     26566
9172082                                              genus     26168
4934671                         List of districts of India     25309
...                                                    ...       ...
3886517                                    Ingemar Wollert         1
3886549                  Ingenheim (Billigheim-Ingenheim)          1
3886551                                        Ingenhouzia         1
3886552                                 Ingenia (magazine)         1
3886573                                 Ingeniero Thompson         1
3886588                                     Ingenieurkorps         1
3886587                                  Ingenieurgeologie         1
3886585                                     IngenieurbÃ¼ro         1
3886584                 Ingenieur-BÃ¼ro Strauber-Frommholf         1
3886583          Ingenieur-BÃ¼ro Strauber - Frommhold Gmbh         1
3886582                           Ingenieur Kontor LÃ¼beck         1
3886581                       Ingenieur BÃ¼ro Stengel GmbH         1
3886579                                IngenierÃ­a militar         1
3886577                                Ingenieros de Oruro         1
3886576                                    Ingenieros F.C.         1
3886574                               Ingeniero V. BalbÃ­n         1
3886572                                 Ingeniero Silveyra         1
3886553                                  Ingenia mirabilis         1
3886570                         Ingeniero Luis B. SÃ¡nchez         1
3886568                      Ingeniero Industrial (glider)         1
3886567                       Ingeniero Francisco MurguÃ­a         1
3886566                                  Ingeniero Foster          1
3886565                          Ingeniero Cassafousth Dam         1
3886564                 Ingeniero Carlos FernÃ¡ndez Casado         1
3886561  Ingeniero Ambrosio L V Taravella International...         1
3886560                                          Ingeniero         1
3886559                                     Ingenico Group         1
3886558           Ingenic Semiconductor#XBurst1-based SoCs         1
3886555                                           Ingeniat         1
9655164                                               ð«         1

[9655165 rows x 2 columns]

In [65]:
df_title_count.describe()

           in_count
count  9.655165e+06
mean   4.875887e+00
std    1.005153e+02
min    1.000000e+00
25%    1.000000e+00
50%    1.000000e+00
75%    2.000000e+00
max    7.929200e+04

In [54]:
df_count_by_count = pd.DataFrame(df_title_count.groupby('in_count').in_count.count())

In [56]:
df_count_by_count.columns = ['link']
df_count_by_count = df_count_by_count.reset_index()
df_count_by_count.columns = ['count', 'in_count']

In [70]:
df_count_by_count = df_count_by_count.sort_values(['count'], ascending=[1])

In [71]:
df_count_by_count

      count  in_count
0         1   6133435
1         2   1448269
2         3    600666
3         4    336680
4         5    208796
5         6    145639
6         7    106617
7         8     80978
8         9     63738
9        10     51641
10       11     42438
11       12     35600
12       13     30262
13       14     26416
14       15     22376
15       16     19944
16       17     17634
17       18     15681
18       19     14047
19       20     12952
20       21     11484
21       22     10412
22       23      9501
23       24      8659
24       25      8047
25       26      7433
26       27      6932
27       28      6402
28       29      5888
29       30      5703
...     ...       ...
2694  25309         1
2695  26168         1
2696  26566         1
2697  27134         1
2698  27188         1
2699  27558         1
2700  28296         1
2701  29221         1
2702  29421         1
2703  30296         1
2704  31774         1
2705  31867         1
2706  34160         1
2707  34521         1
2708  34668         1
2709  34880         1
2710  35283         1
2711  39231         1
2712  39553         1
2713  41628         1
2714  42947         1
2715  46853         1
2716  54656         1
2717  54693         1
2718  58224         1
2719  59854         1
2720  63203         1
2721  63259         1
2722  68096         1
2723  79292         1

[2724 rows x 2 columns]

In [64]:
df_count_by_count.describe()

              count      in_count
count   2724.000000  2.724000e+03
mean    2624.078561  3.544481e+03
std     5130.918459  1.215843e+05
min        1.000000  1.000000e+00
25%      681.750000  1.000000e+00
50%     1393.500000  2.000000e+00
75%     2618.250000  1.000000e+01
max    79292.000000  6.133435e+06

In [67]:
df_count_by_count.to_csv(PATH_TO_DATA_EN+'enwiki-20180620-red_count_by_count.csv', index = False, encoding='ISO-8859-1', quotechar="'", escapechar ="\\")